### ISSUE TITLE
L8 band name allocation is wrong

### ISSUE THREAD

**Issue by zaib2019** [yanghuikang/Landsat-LAI#3]
Just a comment, I found a mistake in the band rename sequence for Landsat 8, this affects indices retrievals.

**Comment by yanghuikang** [comment]
Thank you for checking the code and bringing up this issue! Just to clarify, is this the line in question? 
https://github.com/yanghuikang/Landsat-LAI/blob/795779b1e7f4159fcab869b1e4453a5639ca8848/scripts/ee_Landsat_LAI_export_v0.1.1.py#LL82C1-L87C76
It seems to be working correctly, as ".compare()" returns 0 when the strings are identical. Just tested the code and the output looked alright.
Please feel free to let me know if I misunderstood your concern or if there are any further issues!
